default window size:
    x: 512
    y: 512

keep aspect ratio: no

refresh rate: 60

palettes:
	low:
        - 000000 # BLOCK
        - 404040 # CROSS
        - 404000 # WIRE
        - 404040 # LIGHT
        - 800000 # AND
        - 008000 # OR
        - 000080 # XOR
        - 008080 # NAND
        - 800080 # NOR
        - 808000 # XNOR
        - 004080 # IO PORT
        - 400080 # CLOCK
        - 804000 # T--LATCH
        - 408000 # RS-LATCH
        - 800040 # D--LATCH
        - 008040 # JK-LATCH
        - 004000 # MEMORY
        - 400000 # JUMPER
        
    high:
        - 000000 # BLOCK
        - 404040 # CROSS
        - ffff80 # WIRE
        - ffffff # LIGHT
        - ff0000 # AND
        - 00ff00 # OR
        - 0000ff # XOR
        - 00ffff # NAND
        - ff00ff # NOR
        - ffff00 # XNOR
        - 0080ff # IO PORT
        - 8000ff # CLOCK
        - ff8000 # T--LATCH
        - 80ff00 # RS-LATCH
        - ff0080 # D--LATCH
        - 00ff80 # JK-LATCH
        - 004000 # MEMORY
        - 400000 # JUMPER

